### ISSUE TITLE
Enhanced Cover Art Uploads doesn't run on seeded pages in Tampermonkey

### ISSUE THREAD

**Issue by tigerman325** [ROpdebee/mb-userscripts#145]
For some reason, it is no longer working for me from the a-tisket feed. I click on add to release and it goes to the right spot, but then nothing happens. The box to manually add it is also just not there. I can refresh, nothing. Oddly, If I close the tab and then go back to the release and then to add artwork, the box appears and I can add.

**Comment by ROpdebee** [comment]
Do you use Tampermonkey? I think this is the same root cause as #59 and the main reason why #75 is needed. I think it was introduced in #72, which changes the way cover art is seeded from a-tisket to MB.

Could you check whether [this version](https://raw.github.com/ROpdebee/mb-userscripts/dist-preview-146/mb_enhanced_cover_art_uploads.user.js) fixes the problem? If it does, you can probably continue using that version, it should continue to automatically update.
