### ISSUE TITLE
Support other languages on ISWCNet

### ISSUE THREAD

**Issue by clorirdrix** [ROpdebee/mb-userscripts#18]
Hi, I'm trying to use your script, (chrome latest version with Tampermonkey) and when I click "copy work code" on ISWC, it doesnt get any info at all and when I tried to paste with the button it always report "Log - No data found. Did you copy anything?" Is there something I don't do right, sorry I might not be an Issue, probably an error on my part.

Also, I've tried with Firefox (greasemonky) and Vivaldi (violentmonkey)... always the same issue

**Comment by ROpdebee** [comment]
Hi! Is there anything logged in the [tab's console|https://developer.chrome.com/docs/devtools/open/#console]? Which language are you using on ISWCNet?

**Comment by clorirdrix** [comment]
Ok, I figured it was the french language that was problematic. Thanks for the input, works like a charm now!

**Comment by ROpdebee** [comment]
Cool! I'm going to keep this open as a reminder to either fix the script on non-English pages, or clarify that it only works on English pages.

**Comment by jesus2099** [comment]
I confirm this.
I don't know why I cannot switch to English at the moment, so the **Copy works code** button (should be renamed to **Copy work codes** BTW) is above Title variations instead of above Work codes and clicking it says (console):

    Uncaught TypeError: Cannot read property 'innerText' of null

https://iswcnet.cisac.org/search?iswc=T7035811088
https://iswcnet.cisac.org/search?iswc=T7035820512

**Comment by ROpdebee** [comment]
Sorry, I completely overlooked your reply 😳 

I've done some digging, it turns out it's possible to just get the correct translations automatically by requesting `https://iswcnet.cisac.org/configuration/GetLocalizedStrings?culture=fr` (and `es` for Spanish, I guess). That seems like a more reliable option to go with here, but thanks for the offer to translate :)

Ultimately I'd prefer to use IDs and class names, but they seem generated (like `ViewMore_grid__tmv_Y`) and I'm not sure whether it's safe to rely on them not changing often.

**Comment by ROpdebee** [comment]
Actually, it seems translations are stored in `localStorage.strings`, so it could possibly just use that.
