### ISSUE TITLE
MB: QoL: Seed the batch recording comments script

### ISSUE THREAD

**Issue by tigerman325** [ROpdebee/mb-userscripts#21]
I ran a test on a release. Just wanted to let you know the script doesn't work if there is more than one date on recordings. 

https://musicbrainz.org/edit/80062461

**Comment by ROpdebee** [comment]
Fixed in 2021.6.2.
The script will now refuse to update comments if there are conflicting dates, places, or areas in the ARs, or if the new comment differs significantly from the existing comment. It may be a bit overzealous in some cases, but it's better to be safe than sorry. It will also keep the credited name of a venue, if present.
