### ISSUE TITLE
Same picture is reloaded

### ISSUE THREAD

**Issue by jesus2099** [ROpdebee/mb-userscripts#3]
Twice the same picture: https://musicbrainz.org/release/d5022396-b0d8-4378-ac38-8151ab96558c/edits

Just if it's easy to store results in page for next time there is same picture on same page (usually edit list):
https://github.com/ROpdebee/mb-userscripts/blob/4570caa02068458a9693827d357e6f18d0fd1c01/mb_caa_dimensions.user.js#L92

If not easy for you (for me, it's not easy), please quickly close as wontfix. :)

**Comment by jesus2099** [comment]
Don't forget the version up to allow auto-update for users. :)

**Comment by ROpdebee** [comment]
Fixed by using a promise rather than simple callbacks and caching promises on a per-url basis. Second image would just `.then()` the previous promise, which works even when the promise is already resolved.

I hadn't bumped the version yet, since I wanted to take a stab at caching the results across pages too, but there's some challenges (#4) that I need to think about a bit more.

**Comment by jesus2099** [comment]
Woah, I never could understand JavaScript promises and the whole new style syntax that came around the same time.
