### ISSUE TITLE
Display image dimensions and size for RG cover art

### ISSUE THREAD

**Issue by kellnerd** [ROpdebee/mb-userscripts#439]
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/57

> I don’t remember if it ever worked in either case but on “set cover art” pages neither dimension nor size are displayed and on release group pages size is always “??? KB”:
> - https://musicbrainz.org/release-group/e722cfc7-0975-4a33-82dd-bf37cc714321
> - https://musicbrainz.org/release-group/ab26a2e1-76bf-4007-ac86-8f064d456a8a/set-cover-art

**Comment by ROpdebee** [comment]
The RG size issue has been around forever, it's because the size is loaded from the IA metadata, which is release-specific. To fix it, we'd need to extract which release the RG image belongs to (which is probably possible somehow). Not sure about the "set cover art" page issue.

Probably needs a TS rewrite first though 🙂
