### ISSUE TITLE
Idea: fill track lengths from Bandcamp

### ISSUE THREAD

**Issue by rigrig** [ROpdebee/mb-userscripts#583]
Sometimes albums are added to MusicBrainz while only available for pre-order on Bandcamp.
In those cases not all track lengths are available yet, so they need to be filled in later when the album becomes available.
[Example edit](https://musicbrainz.org/edit/93548732)

The only two ways I've found to do this are 
1. Fill in all times by hand -> tedious (and times as listed on Bandcamp often seem to be off by a second)
2. After downloading the album, use a Picard plugin to export the tracklist and use the track parser -> this also overwrites titles, which usually means the capitalization needs fixing (again).

It would be nice if the Tracklist tab for releases with a Bandcamp page had a button to "Fill missing lengths from Bandcamp" (And similar for other sources I guess)

**Comment by kellnerd** [comment]
I'm using the Time Parser feature of https://github.com/jesus2099/konami-command/blob/master/mb_SUPER-MIND-CONTROL-II-X-TURBO.user.js to alter only the track lengths but not the track titles. It's not specifically for Bandcamp, you can feed it any text blurb which contains track lengths.

Or I simply wait until the tracklist on Bandcamp is complete before I do the import, but that does not help if someone else already imported the incomplete tracklist.

**Comment by ROpdebee** [comment]
Thanks for the suggestion! However, I'm going to close this issue since the script mentioned by kellnerd above already provides a reasonable solution to this. If you still think a button should be added to the Bandcamp page, I suggest opening a new issue in https://github.com/murdos/musicbrainz-userscripts, where the Bandcamp importer lives, as in my opinion, it makes more sense to include such a feature in that userscript instead of creating an entirely new one.
