### ISSUE TITLE
Userscript Idea: Quick-fill (p) & (c)

### ISSUE THREAD

**Issue by ROpdebee** [ROpdebee/mb-userscripts#77]
It shouldn't be too difficult to parse most of the (p) and (c) credits from a-tisket, and there aren't that many people actually filling them in. It takes quite a few clicks to fill them though. Could we speed that up a bit?

**Comment by tigerman325** [comment]
I'd love this. It seems that most editors just leave this in the annotation because a-tisket puts it there (why this ever started, was purely marlonob's own preference). Even many autoeditors aren't taking the time to move them to the relationships. Maybe if there was a tie-in to a-tisket, like the cover art or texke's new release events script (in which he credits you for inspiration).

**Comment by kellnerd** [comment]
@tigerman325 A demo version is now available in my repository: [Parse Copyright Text](https://github.com/kellnerd/musicbrainz-bookmarklets#parse-copyright-text)
Since I had experimented with the relationship editor for my other new userscript, I already had half of the code and decided to put this together today.

Currently it only supports release-label relationships, but it shouldn't be too difficult to add the (P) relationships to all recordings of the release at a later stage. But first I want to make sure that it correctly parses all kinds of copyright text.

Also the initial UI is not great, it is just an additional (+) icon button in the relationship editor which opens a pop-up to enter the copyright blurb.
Then the userscript opens an add relationship dialog and fills it for you, you only have to select the correct label from the already opened search dropdown (in automatic mode you don't even have to do that). In case there are multiple labels, it waits for you to close the dialog before it opens the next one.
I am open for suggestions how to improve the UI.

Since I am not adding copyright relationships that often, I would love if you could help me to collect a range of different text formats and test them. I already have written down a few basic [test cases](https://github.com/kellnerd/musicbrainz-bookmarklets/blob/main/test/parseCopyright.test.js) but I am sure there are a lot more which are not covered yet (e.g. (P) This compilation).

**Comment by tigerman325** [comment]
So far working well. One issue that some editors might not like is that it fills the "credited as" field with a label name even if it's the exact same. Usually that would be left blank. I'll let you know if I run into any issues with formatting. So far, I haven't.

**Comment by tigerman325** [comment]
This one didn't work as far as adding the licensed to, it only worked for (P) & (C):
℗ & © «2016 Maspeth Music BV, under exclusive license to Republic Records, a division of UMG Recordings, Inc. (Eddie O Ent.)»

**Comment by tigerman325** [comment]
Doesn't add licensed to, but did add (P) & (C):
© 2021 SSA Recording, LLP, under exclusive license to Republic Records, a division of UMG Recordings, Inc. ℗ 2021 SSA Recording, LLP, under exclusive license to Republic Records, a division of UMG Recordings, Inc.

**Comment by tigerman325** [comment]
Same:
℗ «2021 SSA Recording, LLP, under exclusive license to Republic Records, a division of UMG Recordings, Inc.»

**Comment by tigerman325** [comment]
I just noticed that on SSA Recording, LLP, on all the above, that only SSA Recording is going into the search field. The LLP is being chopped off.

**Comment by tigerman325** [comment]
HD Tracks API: Worked for (P) & (C), but cut off "Inc. and only searched for "The Weeknd XO". Distributed by didn't search at all.
"pLine": "Distributed By Republic Records.; ℗ 2011 The Weeknd XO, Inc.",
"cLine": "© 2011 The Weeknd XO, Inc.",

**Comment by tigerman325** [comment]
HDTracks API distributor line doesn't work at all (not that I expected it too).
"distributor": "Universal Music Group

**Comment by tigerman325** [comment]
Didn't work without any dates:
℗ & © «Rare»

**Comment by tigerman325** [comment]
All of "Magic Quid Limited under exclusive licence to BMG Rights Management (UK) Limited" went into search and credited as.
℗ & © «2019 Magic Quid Limited under exclusive licence to BMG Rights Management (UK) Limited»

**Comment by kellnerd** [comment]
Many thanks for your comments, I should have created a proper place to collect these examples immediately, sorry for the flood of messages @ROpdebee.
Now I have started a [dedicated wiki page](https://github.com/kellnerd/musicbrainz-bookmarklets/wiki/Parse-Copyright-Notices) in my repository which you should be able to edit.

**Comment by tigerman325** [comment]
Just now when I tried the following, only the phonographic copyright was added:
© «2017 The Media Champ»
℗ «2003 The Media Champ»

It was working before, but I think it's because of the cache. I had another release that had the same label, but only a phonographic copyright line and I had to do a search. When I entered this, it didn't do a search and just added this as a phonographic copyright and ignored the copyright line entirely. I like the fact that it just adds the label once you've found it before, but obviously, this wasn't intended.

**Comment by tigerman325** [comment]
Is there a way to clear previously found labels and force a new search? Example: ℗ & © «1977 Capitol Records, LLC»
I had a release that was previously just "Capitol Records" then a release that had the LLC, but it doesn't give me a chance now to search for the LLC, it just auto fills Capital Records without the LLC.

**Comment by ROpdebee** [comment]
Thanks @kellnerd
