### ISSUE TITLE
CAA Dimensions blocks edits

### ISSUE THREAD

**Issue by psychoadept** [ROpdebee/mb-userscripts#8]
I love the idea of this extension but I had to disable it because I can't submit ANYTHING on MB website while it's active: edits, votes, edit notes, etc. I always get this message, and clicking continue doesn't do anything. I know this was implemented recently to fix some security issues, but normally only affects things like the discogs release seeder.

![2021-02-18_17-03-03](https://user-images.githubusercontent.com/10135275/108433298-6040d380-720b-11eb-8062-32b6916308d3.png)

**Comment by psychoadept** [comment]
For what it's worth, I'm using Vivaldi but have all the ad and tracker blocking turned off for MusicBrainz.

**Comment by ROpdebee** [comment]
I cannot reproduce this on Vivaldi 3.5.2115.81 with TamperMonkey v4.11. What userscript engine are you using to load it?

Frankly, it would surprise me if this userscript could cause issues like this, since it doesn't (or at least shouldn't) tamper with any forms. It appears that the origin header is being removed from the form submission, which is something that this script should not be doing.

**Comment by psychoadept** [comment]
It's definitely related to this script, I went through every script that was active, turning them off and on to test. I'm also using Tampermonkey 4.11, but I'm on Vivaldi 3.6.2165.36 which has introduced some other weird bugs that I've noticed. It's entirely possible the bug is with Vivaldi but I think you have a better chance than me of diagnosing exactly where things are going wrong.

**Comment by psychoadept** [comment]
Just to triple check, I went back and turned off ALL other scripts, even ones that wouldn't be active on that page. Interestingly, that seems to have cleared it up. Which means there's something about your script alongside another script or scripts. I'll let you know when I figure out more.

**Comment by psychoadept** [comment]
test

**Comment by psychoadept** [comment]
Looks like it's an interaction with Preferred MBS (which I thought I had turned off previously, but maybe the script was still impacting the page when I tested). If I turn either one off, it works again. Preferred MBS is hardly a necessity, so I'll turn it off for now.

**Comment by psychoadept** [comment]
I posted an issue with jesus2099, too: https://github.com/jesus2099/konami-command/issues/562

**Comment by ROpdebee** [comment]
I've tried with 3.6.2165.36, this script and preferred MBS installed, and setting MBS preference to beta. The closest I've come to reproducing this issue is by opening an edit on the main site and submitting a vote, which then redirects to the beta site and shows such a warning page. Importantly though, the origin is set to musicbrainz.org, not `null`, and it still happens when CAA dimensions is disabled.

As far as I can tell, that warning page is generated when the MB server receives a form submission with the HTTP Origin header (or Referrer?) that differs from the domain on which the request is received. E.g., for the release seeder, the request originates from `discogs.com`, which is different from `musicbrainz.org` and therefore leads to the warning. Similarly, in my case, the origin would be `musicbrainz.org` while the target is `beta.musicbrainz.org` (whether that should lead to a warning is outside the scope of this issue). In your case, the Origin header seems to be set to `null`. Some extensions remove origin headers for cross-domain requests to prevent tracking etc. That still doesn't explain why it works with either of the two scripts enabled, but not when both are enabled.

Do you use any of such extensions? Does this issue still happen when submitting a form directly on `beta.musicbrainz.org`? Does it happen on pages that do not contain any cover art at all? Does the console show anything out of place?

**Comment by ROpdebee** [comment]
@psychoadept Are you still facing this issue?
